[project]
name = "reachy"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = "==3.13.*"
dependencies = [
    "fugashi[unidic-lite]>=1.5.2",
    "langdetect>=1.0.9",
    "mecab-python3>=1.0.12",
    "misaki[ja,zh]>=0.9.4",
    "mlx-audio[tts]==0.3.1",
    "mlx-lm>=0.30.5",
    "pip>=26.0",
    "rich>=14.3.1",
    "sounddevice>=0.5.3",
    "soundfile>=0.12.0",
    "typer>=0.21.1",
]

[tool.ruff]
target-version = "py313"

[tool.ruff.lint]
select = [
    "F",    # Pyflakes
    "E",    # pycodestyle errors
    "W",    # pycodestyle warnings
    "I",    # isort
    "UP",   # pyupgrade
    "B",    # flake8-bugbear
    "SIM",  # flake8-simplify
    "C4",   # flake8-comprehensions
    "RET",  # flake8-return
    "PTH",  # flake8-use-pathlib
]
