[project]
name = "reachy"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = "==3.13.*"
dependencies = [
    "mlx-audio[tts]==0.3.1",
    "mlx-lm>=0.30.5",
    "pip>=26.0",
    "rich>=14.3.1",
    "sounddevice>=0.5.0",
    "soundfile>=0.12.0",
    "typer>=0.21.1",
]
